#!/bin/bash -e

# builds the project and creates binaries for pi pico
rm -rf out
mkdir out
cd out
cmake ..
make 

# copies the binaries onto the pico pico (macos)
cp main.uf2 /Volumes/RPI-RP2

# opens up serial monitor for debug
# screen /dev/`ls /dev | grep tty.usbmodem` 115101